# Generated by Django 4.1.6 on 2023-06-08 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_cartdb'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartdb',
            name='Totalprice',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
