# Generated by Django 4.1.6 on 2023-05-19 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('superapp', '0003_registrationdb'),
    ]

    operations = [
        migrations.DeleteModel(
            name='registrationdb',
        ),
    ]
